"""init

Revision ID: ae22d3336822
Revises:
Create Date: 2024-06-13 13:43:54.922133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae22d3336822'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('artwork_id', sa.Integer(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('processed_images',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('source_id', sa.Uuid(), nullable=False),
                    sa.Column('filter_type', sa.String(), nullable=False),
                    sa.Column('settings', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['source_id'], ['images.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_images')
    op.drop_table('images')
    # ### end Alembic commands ###
